services:
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elk_data:/usr/share/elasticsearch/data/
      - ./all-service-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./all-service-config/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options # ini perlu untuk setting Heap Size
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false # nyalakan untuk mengaktifkan autentikasi saat login kibana (5601) ataupun els (9200), password juga bisa di uncomment, tapi perlu downgrade ke 6.8 atau 7.10 untuk semua image tag nya
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch # bisa ganti sesuai keinginan 
      - bootstrap.memory_lock=true
#      - ELASTIC_PASSWORD=CNk6jg4usvM3PdWN
#      - ELASTICSEARCH_USERNAME=elastic
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - elk_networks

  logstash:
    image: logstash:7.16.1
    container_name: logstash
    environment:
      - discovery.seed_hosts=logstash
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./all-service-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./all-service-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./all-service-config/logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - ls_data:/usr/share/logstash/data
    networks:
      - elk_networks
    depends_on:
      elasticsearch:
        condition: service_healthy

  kibana:
    image: kibana:7.16.1
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./all-service-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 5      
    networks:
      - elk_networks
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: elastic/filebeat:7.16.1
    container_name: filebeat
    user: root
    volumes:
      - ./all-service-config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./syslog:/var/log/syslog:ro
      - ./auth.log:/var/log/auth.log:ro
      - ./all-service-config/filebeat/filebeat-entrypoint.sh:/usr/local/bin/filebeat-entrypoint.sh:ro
    entrypoint: ["/usr/local/bin/filebeat-entrypoint.sh", "filebeat", "-e", "--strict.perms=false"]
    networks:
      - elk_networks
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_started

networks:
  elk_networks:
    driver: bridge

volumes:
  elk_data:
  ls_data:
  kb_data: